googleAnalytics = "G-0X445MC3NJ"

baseURL = "https://ryanwildes.github.io/fantiepedia"
languageCode = "en-us"
title = "Fantiepedia"
theme = "hugo-book"

enableGitInfo = true

enableRobotsTXT = true

[sitemap]
  changefreq = ""
  filename = "sitemap.xml"
  priority = 0.5

[menu]
[[menu.after]]
  name = "GitHub"
  url = "https://github.com/ryanwildes/fantiepedia"
  weight = 99

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]

  BookTheme = "dark"

  BookSection = "*"

  BookRepo = "https://github.com/ryanwildes/fantiepedia"
  BookCommitPath = "commit"

  BookSearch = true